import { useState, useEffect } from 'react'
import { fetchTransparency } from '../api'
import type { TransparencyStats } from '../types'

interface Props {
  score: number
}

function band(score: number) {
  if (score <= 40)
    return { color: 'bg-accent-600', text: 'text-accent-700', label: 'Low readiness', ring: '#0d9488' }
  if (score <= 70)
    return { color: 'bg-amber-500', text: 'text-amber-600', label: 'Moderate readiness', ring: '#f59e0b' }
  return { color: 'bg-brand-600', text: 'text-brand-700', label: 'High readiness', ring: '#4f46e5' }
}

/**
 * Readiness score display with SVG progress ring and gradient text.
 * The ring fills clockwise proportional to the score (0-100).
 */
export default function ReadinessScore({ score }: Props) {
  const b = band(score)
  const [showHow, setShowHow] = useState(false)
  const [stats, setStats] = useState<TransparencyStats | null>(null)

  useEffect(() => {
    let active = true
    fetchTransparency().then(res => {
      if (active) setStats(res)
    }).catch(() => {})
    return () => { active = false }
  }, [])

  // SVG ring parameters.
  const radius = 52
  const stroke = 6
  const circumference = 2 * Math.PI * radius
  const offset = circumference * (1 - score / 100)

  return (
    <div className="rounded-xl border border-slate-200 bg-gradient-to-br from-white to-slate-50 p-6 text-center">
      {/* SVG progress ring */}
      <div className="relative mx-auto" style={{ width: 130, height: 130 }}>
        <svg width="130" height="130" className="absolute inset-0 -rotate-90">
          {/* Background ring */}
          <circle
            cx="65" cy="65" r={radius}
            fill="none"
            stroke="#e2e8f0"
            strokeWidth={stroke}
          />
          {/* Filled arc */}
          <circle
            cx="65" cy="65" r={radius}
            fill="none"
            stroke={b.ring}
            strokeWidth={stroke}
            strokeLinecap="round"
            strokeDasharray={circumference}
            strokeDashoffset={offset}
            style={{ transition: 'stroke-dashoffset 1s ease-out' }}
          />
        </svg>
        {/* Score number inside the ring */}
        <div className="absolute inset-0 flex flex-col items-center justify-center">
          <span
            className="text-5xl font-extrabold"
            style={{
              background: `linear-gradient(135deg, ${b.ring}, ${b.ring}cc)`,
              WebkitBackgroundClip: 'text',
              WebkitTextFillColor: 'transparent',
            }}
          >
            {score}
          </span>
        </div>
      </div>

      <div className="mt-2 text-sm font-semibold uppercase tracking-wide text-slate-500">Readiness Score</div>
      <div className={`mt-0.5 text-xs font-semibold ${b.text}`}>{b.label}</div>

      {/* Linear progress bar */}
      <div className="mt-4 h-2 w-full overflow-hidden rounded-full bg-slate-100">
        <div className={`h-full rounded-full transition-all duration-700 ${b.color}`} style={{ width: `${Math.max(4, score)}%` }} />
      </div>
      <div className="mt-1.5 flex justify-between text-[10px] font-medium text-slate-500">
        <span>0</span><span>40</span><span>70</span><span>100</span>
      </div>

      {/* How This Works Panel */}
      <div className="mt-4 border-t border-slate-200 pt-3">
        <button 
          onClick={() => setShowHow(!showHow)}
          className="text-xs font-semibold text-brand-600 hover:text-brand-700 flex items-center justify-center w-full gap-1"
        >
          {showHow ? '▴ Hide' : '▾ How This Works'}
        </button>
        {showHow && (
          <div className="mt-3 text-left text-[11px] text-slate-600 space-y-3 bg-white p-3 rounded-lg border border-slate-200 shadow-sm animate-fade-in">
            <p>
              This Readiness Score is a composite generated by a deterministic, auditable checklist rules engine layered on top of two trained machine learning models.
            </p>
            {stats?.eda_report ? (
              <ul className="list-disc pl-4 space-y-1">
                <li>Models are trained on the full historical dataset of <strong>{stats.eda_report.row_count.toLocaleString()} rows</strong> (0 nulls).</li>
                <li>
                  <strong>Closure Probability:</strong> RandomForestClassifier (ROC-AUC <strong>{stats.model_metrics?.closure_model?.roc_auc?.toFixed(3)}</strong>). 
                  <span className="block mt-1 text-slate-700 italic bg-slate-50 p-1.5 rounded">
                    "Recall on actual road closures improved from 16.8% to 53.8% after correcting for class imbalance in training (closures are only 7.4% of all incidents)."
                  </span>
                </li>
                <li>
                  <strong>Predicted Duration:</strong> RandomForestRegressor (MAE <strong>{stats.model_metrics?.duration_model?.mae?.toFixed(3)} hours</strong>, R² <strong>{stats.model_metrics?.duration_model?.r2?.toFixed(3)}</strong>).
                </li>
              </ul>
            ) : (
              <p className="italic text-slate-400">Loading model metrics...</p>
            )}
          </div>
        )}
      </div>
    </div>
  )
}
